---
sidebar: sidebar 
permalink: concept-deploy-netapp-console-local.html 
keywords: deploy, install, vCenter, Linux, high availability, deployment options, netapp console local 
summary: Conoce las opciones de implementación local de NetApp Console, incluidas las instalaciones en vCenter y Linux. 
---
= Opciones de implementación para la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Instala la implementación local de NetApp Console en tu entorno vCenter.



[[install-in-your-vcenter-environment]]
=== Instálalo en tu entorno de vCenter

Implementa NetApp Console localmente como un dispositivo virtual en tu entorno VMware vCenter usando una imagen OVA preconfigurada.

link:task-install-agent-on-prem-ova.html["Instala la implementación local de NetApp Console en tu entorno de vCenter"].



[[next-steps]]
== Próximos pasos

Después de la implementación, completa las siguientes tareas para empezar:

* link:task-add-systems.html["Agrega sistemas de almacenamiento a la implementación local de NetApp Console"]
* link:task-iam-manage-members-permissions.html["Agrega miembros y asigna roles en la implementación local de NetApp Console"]

