---
permalink: legal-notices.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Avisos legales para la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Documentación de implementación local de NetApp Console para esta página.

[role="lead"]
Los avisos legales proporcionan acceso a declaraciones de derechos de autor, marcas registradas, patentes y más.



[[copyright]]
== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



[[trademarks]]
== Marcas registradas

NETAPP, el logotipo de NETAPP y las marcas que aparecen en la página de NetApp Trademarks son marcas comerciales de NetApp, Inc. Otros nombres de empresas y productos pueden ser marcas comerciales de sus respectivos propietarios.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



[[patents]]
== Patentes

Una lista actual de patentes propiedad de NetApp se puede encontrar en:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



[[privacy-policy]]
== Política de privacidad

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



[[open-source]]
== Código abierto

Los archivos de aviso proporcionan información sobre los derechos de autor y las licencias de terceros utilizadas en el software NetApp.

link:media/notice.pdf["Aviso para la NetApp Console"^].
