---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, Organization admin, Folder or fleet admin, Super admin, Federation admin, platform roles, role, iam, identity and access management, netapp console local 
summary: Asigna roles de la plataforma a los usuarios para conceder permisos para gestionar la implementación local de NetApp Console, asignar roles, añadir usuarios y gestionar federaciones. 
---
= NetApp roles de acceso a la plataforma de implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Asigna roles de la plataforma a los usuarios para conceder permisos para gestionar la implementación local de la NetApp Console, asignar roles, añadir usuarios, crear flotas y gestionar la autenticación de usuarios.

.Ejemplo de funciones organizativas para una gran empresa multinacional
XYZ Corporation organiza el acceso al almacenamiento de datos por regiones—América del Norte, Europa y Asia-Pacífico—, proporcionando control regional con supervisión centralizada.

El *administrador de la organización* en la implementación local de la Console de XYZ Corporation crea una organización inicial y carpetas independientes para cada región. El *administrador de carpetas o flotas* de cada región organiza las flotas (con los recursos asociados) dentro de la carpeta de la región.

Los administradores regionales con el rol de *Administrador de carpetas o flotas* gestionan activamente sus carpetas añadiendo recursos y usuarios. Estos administradores regionales también pueden añadir, eliminar o renombrar las carpetas y flotas que gestionan. El *Administrador de la organización* hereda los permisos para cualquier recurso nuevo, manteniendo la visibilidad del uso del almacenamiento en toda la organización.

Dentro de la misma organización, a un usuario se le asigna el rol de *Federation admin* para gestionar la federación de la organización con su IdP corporativo. Este usuario puede añadir o eliminar organizaciones federadas, pero no puede gestionar usuarios ni recursos dentro de la organización. El *Organization admin* asigna a un usuario el rol de *Federation viewer* para que compruebe el estado de la federación y vea las organizaciones federadas.

Las siguientes tablas indican las acciones que puede realizar cada rol de la plataforma de implementación local de Console.



[[organization-administration-roles]]
[[organization-admin-roles]]
== Funciones de administración de la organización

[cols="2,1,1"]
|===
| Tarea | Administrador de la organización | Administrador de carpetas o de flotas 


| Crear, modificar o eliminar sistemas desde la implementación local de la NetApp Console (añadir o descubrir sistemas) | Sí | Sí 


| Crear carpetas y flotas, incluida la eliminación | Sí | No 


| Cambiar el nombre de las carpetas y flotas existentes | Sí | Sí 


| Asignar roles y añadir usuarios | Sí | Sí 


| Asocia recursos con carpetas y flotas | Sí | Sí 


| Regístrate para recibir asistencia y envía tus incidencias a través de la Console | Sí | Sí 


| Utiliza servicios de datos que no estén asociados a un rol de acceso explícito | Sí | Sí 


| Consulta la página de auditoría y las notificaciones | Sí | Sí 


| Configura la integración de LLM y activa el asistente de NetApp Console | Sí | No 


| Configura el envío de notificaciones y la configuración del servidor de correo electrónico | Sí | No 
|===


[[federation-roles]]
== Funciones de la federación

[cols="2,1,1"]
|===
| Tarea | Administrador de la federación | Visor de la federación 


| Crear y actualizar integraciones de servicios de directorio | Sí | No 


| Ver federaciones y sus detalles | Sí | Sí 
|===


[[super-admin-and-viewer-roles]]
[[super-admin-roles]]
== Roles de superadministrador y de visualizador

El rol de *Super admin* ofrece acceso completo para gestionar las funciones de Console, el almacenamiento y los servicios de datos. Este rol es adecuado para quienes supervisan la administración y la gobernanza. Por el contrario, el rol de *Super viewer* ofrece acceso de solo lectura, ideal para auditores o partes interesadas que necesitan visibilidad sin realizar cambios.

Las organizaciones deben utilizar el acceso de *Super admin* con moderación para minimizar los riesgos de seguridad y alinearse con el principio del privilegio mínimo. La mayoría de las organizaciones deberían asignar roles detallados con solo los permisos necesarios para reducir el riesgo y mejorar la auditabilidad.

.Ejemplo de superroles
ABC Corporation cuenta con un pequeño equipo de cinco personas que utiliza la NetApp Console para servicios de datos y gestión del almacenamiento. En lugar de distribuir múltiples roles, asignan el rol de *Super admin* a dos miembros sénior del equipo, quienes se encargan de todas las tareas administrativas, incluida la gestión de usuarios y la configuración de recursos. A los tres miembros restantes del equipo se les asigna el rol de *Super viewer*, lo que les permite supervisar la salud del almacenamiento y el estado de los servicios de datos sin poder modificar la configuración.

[cols="2,1"]
|===
| Función | Roles heredados 


 a| 
Súper administrador
 a| 
* Administrador de la organización
* Administrador de carpetas o de flotas
* Superadministrador de backup and recovery
* Administrador de almacenamiento




 a| 
Súper visualizador
 a| 
* Visor de organización
* Visor de copias de seguridad
* Visor de almacenamiento


|===