---
sidebar: sidebar 
permalink: reference-ports-on-prem.html 
keywords: networking, network requirements, ports, on-premises, TCP, UDP, firewall, connectivity requirements, Console local, Console local connectivity, netapp console local, inbound ports, OVA 
summary: El archivo OVA de implementación local de la NetApp Console gestiona su propio cortafuegos interno. Si tu entorno aplica una política de cortafuegos externo a la VM, asegúrate de que se pueda acceder a los siguientes puertos de entrada desde tus hosts de gestión. 
---
= Puertos de entrada para la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El archivo OVA de implementación local de la NetApp Console gestiona su propio cortafuegos interno. Si tu entorno aplica una política de cortafuegos externo a la VM, asegúrate de que se pueda acceder a los siguientes puertos de entrada desde tus hosts de gestión.

[cols="10,10,80"]
|===
| Puerto | Protocolo | Propósito 


| 22 | TCP | SSH para el mantenimiento remoto y el acceso al shell para diagnóstico 


| 123 | UDP | NTP para la sincronización horaria 


| 2379 | TCP | API de cliente etcd para el tráfico de cliente etcd del plano de control de RKE2 


| 2380 | TCP | Puerto de par de etcd para la replicación entre miembros de etcd 


| 6443 | TCP | Servidor de la API de Kubernetes para el acceso a la API de kubectl y RKE2 


| 8472 | UDP | Superposición VXLAN Canal/Flannel para el tráfico entre pods de los nodos RKE2 


| 9091 | TCP | Punto final de métricas de Calico Felix para el estado y las métricas de CNI 


| 9100 | TCP | Prometheus node_exporter para la recopilación de métricas de host 


| 9345 | TCP | Punto final de registro del supervisor y del servidor RKE2 


| 10250 | TCP | API de Kubelet para metrics-server y kube-apiserver hacia kubelet 
|===