---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: 'NetApp ofrece soporte para la implementación local de NetApp Console de varias maneras. Hay opciones extensas de autoayuda gratuitas disponibles 24x7, como artículos de la base de conocimientos (KB) y un foro de la comunidad. Tu registro de soporte incluye soporte técnico remoto a través de tickets web.' 
---
= Obtén ayuda con la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ofrece soporte para la implementación local de NetApp Console de varias maneras. Hay opciones extensas de auto-soporte gratuitas disponibles 24x7, como artículos de la base de conocimientos (KB) y un foro de la comunidad. Puedes registrarte para soporte con el número de serie de cualquier recurso de almacenamiento asociado con la implementación local de NetApp Console. El registro incluye soporte técnico remoto a través de tickets web.



[[use-self-support-options]]
== Utiliza las opciones de autoservicio

Estas opciones están disponibles de forma gratuita, las 24 horas del día, los 7 días de la semana:

* Documentación
+
La documentación sobre la implementación local de la NetApp Console que estás consultando en este momento.

* https://kb.netapp.com/Cloud/BlueXP["Base de conocimientos"^]
+
Busca en la base de conocimientos de NetApp artículos que te ayuden a resolver problemas.





[[open-a-support-case-with-netapp-console-local-deployment]]
== Abre un caso de soporte técnico con NetApp Console local deployment

Abre un caso de soporte utilizando uno de los números de serie del sistema de almacenamiento NetApp gestionados a través de tu entorno de implementación local de NetApp Console.

.Pasos
. Entra en https://mysupport.netapp.com["Sitio de soporte de NetApp"^] y accede con tus credenciales de soporte técnico de NetApp.
. Selecciona *Casos y partes > Crear caso técnico*.
. Introduce el número de serie del sistema de almacenamiento NetApp asociado con el producto de implementación local de Console que está experimentando el problema.
. Crea un nuevo caso y selecciona el código de categoría adecuado para NetApp Console en una implementación local.




[[download-a-support-bundle]]
== Descargar un paquete de soporte

Un paquete de soporte incluye registros recientes e información de configuración. Puedes descargar el paquete más reciente y enviarlo al soporte técnico de NetApp si te lo piden.

.Pasos
. Selecciona *Administración > Soporte* para ver la página de Soporte.
. En la ficha Soporte, selecciona *Crear* para generar un paquete de registros y datos de configuración.
. Cuando se haya creado el paquete, selecciona *Descargar*. Se te pedirá que descargues un archivo ZIP.
+
El sistema solo mantiene un paquete a la vez. Crear un nuevo paquete de soporte reemplaza el anterior.


