= 
:allow-uri-read: 


Después de instalar y configurar el agente de la consola, añade tus credenciales de la nube para que el agente de la consola tenga los permisos necesarios para realizar acciones en AWS o Azure.

[role="tabbed-block"]
====
.AWS
--
.Antes de empezar
Si acabas de crear estas credenciales de AWS, es posible que tarden unos minutos en estar disponibles. Espera unos minutos antes de añadir las credenciales a la NetApp Console.

.Pasos
. Selecciona *Administración > Credenciales*.
. Selecciona *Organization credentials*.
. Selecciona *Add Credentials* y sigue los pasos del asistente.
+
.. *Ubicación de las credenciales*: Selecciona *Amazon Web Services > Agent*.
.. *Definir credenciales*: Introduce una clave de acceso y una clave secreta de AWS.
.. *Suscripción a Marketplace*: vincula una suscripción a Marketplace con estas credenciales suscribiéndote ahora o seleccionando una suscripción ya existente.
.. *Revisar*: Comprueba los datos de las nuevas credenciales y selecciona *Add*.




Ya puedes ir a https://console.netapp.com["NetApp Console"^] para empezar a usar el agente de Console.

--
.Azure
--
.Antes de empezar
Si acabas de crear estas credenciales de Azure, es posible que tarden unos minutos en estar disponibles. Espera unos minutos antes de añadir las credenciales al agente de la NetApp Console.

.Pasos
. Selecciona *Administración > Credenciales*.
. Selecciona *Add Credentials* y sigue los pasos del asistente.
+
.. *Ubicación de las credenciales*: selecciona *Microsoft Azure > Agente*.
.. *Definir credenciales*: Introduce la información sobre la entidad de servicio de Microsoft Entra que concede los permisos necesarios:
+
*** ID de la aplicación (cliente)
*** ID de directorio (tenant)
*** Secreto del cliente


.. *Suscripción a Marketplace*: vincula una suscripción a Marketplace con estas credenciales suscribiéndote ahora o seleccionando una suscripción ya existente.
.. *Revisar*: Comprueba los datos de las nuevas credenciales y selecciona *Add*.




.Resultado
El agente de la consola ya dispone de los permisos necesarios para realizar acciones en Azure en tu nombre. Ahora puedes acceder a https://console.netapp.com["NetApp Console"^] para empezar a utilizar el agente de la consola.

--
====