= 
:allow-uri-read: 


Crea un rol y asígnalo a una cuenta de servicio que vas a utilizar para la instancia de VM del agente de la Console.

.Pasos
. Crea un rol personalizado en Google Cloud:
+
.. Crea un archivo YAML que incluya los permisos definidos en el link:reference-permissions-gcp.html["Política de agente de consola para Google Cloud"].
.. Desde Google Cloud, activa cloud shell.
.. Sube el archivo YAML que incluye los permisos necesarios para el agente de la Console.
.. Crea un rol personalizado usando el comando  `gcloud iam roles create`.
+
El siguiente ejemplo crea un rol denominado «connector» a nivel de proyecto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentación de Google Cloud: creación y gestión de roles personalizados"^]



. Crea una cuenta de servicio en Google Cloud:
+
.. En el servicio IAM & Admin, selecciona *Cuentas de servicio > Crear cuenta de servicio*.
.. Introduce los datos de la cuenta de servicio y selecciona *Crear y continuar*.
.. Selecciona el rol que acabas de crear.
.. Completa los pasos restantes para crear el rol.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentación de Google Cloud: creación de una cuenta de servicio"^]





.Resultado
Ya tienes una cuenta de servicio que puedes asignar a la instancia de VM del agente de la Console.
