= 
:allow-uri-read: 


.Antes de empezar
Deberías tener lo siguiente:

* Privilegios de root para instalar el agente.
* Detalles sobre un servidor proxy, si se requiere un proxy para el acceso a internet desde el agente.
+
Tienes la opción de configurar un servidor proxy tras la instalación, pero para ello es necesario reiniciar el agente.

* Un certificado firmado por una autoridad de certificación (CA), si el proxy utiliza HTTPS o si el proxy es un proxy de interceptación.


.Acerca de esta tarea
Es posible que el instalador disponible en el NetApp Support Site sea una versión anterior. Después de la instalación, el agente se actualiza automáticamente si hay una nueva versión disponible.

.Pasos
. Si las variables de sistema _http_proxy_ o _https_proxy_ están configuradas en el host, elimínalas:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si no eliminas estas variables del sistema, la instalación fallará.

. Descarga el software del agente desde https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sitio de soporte de NetApp"^] y luego cópialo en el host Linux.
+
Debes descargar el instalador del agente "online" diseñado para su uso en tu red o en la nube.

. Asigna permisos para ejecutar el script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Donde <version> es la versión del agente que descargaste.

. Ejecuta el script de instalación.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Los parámetros --proxy y --cacert son opcionales. Si tienes un servidor proxy, tendrás que introducir los parámetros como se muestra. El instalador no te pide que proporciones información sobre un proxy.

+
Aquí tienes un ejemplo del comando usando ambos parámetros opcionales:

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configura el agente para que utilice un servidor proxy HTTP o HTTPS mediante uno de los siguientes formatos:

+
** http://address:port
** \http://nombre-usuario:contraseña@dirección:puerto
** \http://nombre de dominio%92user-name:password@dirección:puerto
** \https://dirección:puerto
** \https://usuario:contraseña@dirección:puerto
** \https://nombre de dominio%92user-name:password@dirección:puerto
+
Ten en cuenta lo siguiente:

+
*** El usuario puede ser un usuario local o un usuario de dominio.
*** En el caso de un usuario de dominio, debes utilizar el código ASCII para una \ como se muestra más arriba.
*** El agente no admite nombres de usuario ni contraseñas que incluyan el carácter @.
*** Si la contraseña incluye alguno de los siguientes caracteres especiales, debes escapar ese carácter especial anteponiéndole una barra invertida: & o !
+
Por ejemplo:

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacert especifica un certificado firmado por una autoridad de certificación (CA) que se utiliza para el acceso HTTPS entre el agente y el proxy. Este parámetro solo es obligatorio si especificas un proxy HTTPS o si el proxy es un proxy de interceptación.

. Si usaste Podman, tendrás que ajustar el puerto de aardvark-dns.
+
.. Conéctate por SSH a la máquina virtual del agente.
.. Abre el archivo _/usr/share/containers/containers.conf_ de podman y modifica el puerto elegido para el servicio DNS de Aardvark. Por ejemplo, cámbialo a 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicia la máquina virtual del agente.




. Espera a que finalice la instalación.
+
Al finalizar la instalación, el servicio del agente (occm) se reinicia dos veces si has especificado un servidor proxy.

. Abre un navegador web desde un host que tenga conexión con la máquina virtual del agente e introduce la siguiente URL:
+
https://_ipaddress_[]

. Después de que inicies sesión, configura el agente:
+
.. Especifica la organización de la NetApp Console que se va a asociar al agente.
.. Introduce un nombre para el sistema.
.. En la sección *¿Estás ejecutando en un entorno seguro?* mantén desactivado el modo restringido.
+
Debes mantener el modo restringido desactivado porque estos pasos describen cómo usar la Consola en modo estándar. Solo debes activar el modo restringido si tienes un entorno seguro y quieres desconectar esta cuenta de los servicios backend de la Consola. Si ese es el caso, link:task-quick-start-restricted-mode.html["Sigue estos pasos para empezar a utilizar la NetApp Console en modo restringido"].

.. Selecciona *Empecemos*.



